import { useState, useEffect } from 'react';
import { supabase } from '../supabase';
import { CARD_BG, ACCENT, GREEN, ORANGE, RED, TEXT, TEXT_MUTED, TEXT_DIM, BORDER, NAV_FONT } from '../theme';

export default function ViolationReport() {
  const [reports, setReports] = useState([]);
  const [clients, setClients] = useState([]);
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ client_id: '', report_date: new Date().toISOString().split('T')[0], violation_type: '', description: '', missed_checkins: 0, last_checkin: '', drug_test_failures: 0, missed_po_visits: 0, missed_court_dates: 0, recommended_action: '', submitted_to: '', status: 'draft' });

  useEffect(() => { fetchReports(); fetchClients(); }, []);

  async function fetchReports() {
    const { data } = await supabase.from('violation_reports').select('*, clients(name)').order('created_at', { ascending: false });
    if (data) setReports(data);
  }

  async function fetchClients() {
    const { data } = await supabase.from('clients').select('id, name').order('name');
    if (data) setClients(data);
  }

  async function handleSave(status = 'draft') {
    setSaving(true);
    const { data: { user } } = await supabase.auth.getUser();
    await supabase.from('violation_reports').insert([{ ...form, provider_id: user.id, status }]);
    setForm({ client_id: '', report_date: new Date().toISOString().split('T')[0], violation_type: '', description: '', missed_checkins: 0, last_checkin: '', drug_test_failures: 0, missed_po_visits: 0, missed_court_dates: 0, recommended_action: '', submitted_to: '', status: 'draft' });
    setShowForm(false);
    setSaving(false);
    fetchReports();
  }

  function printReport(r) {
    const win = window.open('', '_blank');
    win.document.write(`
      <html><head><title>Violation Report</title>
      <style>body{font-family:Arial,sans-serif;padding:40px;max-width:700px;margin:0 auto;}h1{color:#1B3A6B;border-bottom:3px solid #1B3A6B;padding-bottom:12px;}h2{color:#1B3A6B;font-size:14px;text-transform:uppercase;letter-spacing:0.5px;margin-top:24px;}p{color:#333;line-height:1.7;}.field{margin-bottom:12px;}.label{font-weight:bold;color:#555;font-size:13px;}.val{color:#333;font-size:14px;}.warn{background:#fdecea;border-left:4px solid #E74C3C;padding:12px;margin:16px 0;}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #ddd;font-size:12px;color:#888;}</style>
      </head><body>
      <h1>CourtBridge Solutions — Violation Report</h1>
      <div class="field"><span class="label">Generated: </span><span class="val">${new Date().toLocaleString()}</span></div>
      <div class="field"><span class="label">Report Date: </span><span class="val">${r.report_date}</span></div>
      <h2>Client Information</h2>
      <div class="field"><span class="label">Client Name: </span><span class="val">${r.clients?.name || ''}</span></div>
      <h2>Violation Details</h2>
      <div class="field"><span class="label">Violation Type: </span><span class="val">${r.violation_type}</span></div>
      <div class="warn">${r.description}</div>
      <h2>Compliance Summary</h2>
      <div class="field"><span class="label">Missed Check-Ins: </span><span class="val">${r.missed_checkins}</span></div>
      <div class="field"><span class="label">Last Check-In: </span><span class="val">${r.last_checkin || 'None on record'}</span></div>
      <div class="field"><span class="label">Failed Drug Tests: </span><span class="val">${r.drug_test_failures}</span></div>
      <div class="field"><span class="label">Missed PO Visits: </span><span class="val">${r.missed_po_visits}</span></div>
      <div class="field"><span class="label">Missed Court Dates: </span><span class="val">${r.missed_court_dates}</span></div>
      <h2>Recommended Action</h2>
      <div class="field"><span class="val">${r.recommended_action}</span></div>
      ${r.submitted_to ? `<h2>Submitted To</h2><div class="field"><span class="val">${r.submitted_to}</span></div>` : ''}
      <div class="footer">This report was generated by CourtBridge Solutions compliance tracking platform. CourtBridge helps turn participation into proof.</div>
      </body></html>
    `);
    win.document.close();
    win.print();
  }

  const statusColors = {
    draft: { bg: 'rgba(255,140,66,0.15)', color: ORANGE },
    submitted: { bg: 'rgba(91,155,240,0.15)', color: ACCENT },
    reviewed: { bg: 'rgba(76,175,125,0.15)', color: GREEN },
  };

  const inputStyle = { width: '100%', padding: 12, marginBottom: 12, borderRadius: 8, border: `0.5px solid ${BORDER}`, boxSizing: 'border-box', fontSize: 14, background: 'rgba(255,255,255,0.04)', color: TEXT, fontFamily: NAV_FONT };

  return (
    <div style={{ padding: 30, maxWidth: 800, fontFamily: NAV_FONT }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, flexWrap: 'wrap', gap: 10 }}>
        <h1 style={{ color: TEXT, margin: 0 }}>Violation Reports</h1>
        <button onClick={() => setShowForm(!showForm)} style={{ padding: '10px 20px', background: RED, color: 'white', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 14 }}>+ New Violation Report</button>
      </div>
      <p style={{ color: TEXT_MUTED, marginBottom: 24, fontSize: 14 }}>Generate court-ready violation notices when a client fails to meet their compliance requirements.</p>

      {showForm && (
        <div style={{ background: CARD_BG, border: `2px solid ${RED}`, borderRadius: 12, padding: 25, marginBottom: 20 }}>
          <h2 style={{ color: RED, marginBottom: 16, fontSize: 16 }}>⚠️ New Violation Report</h2>
          <select value={form.client_id} onChange={e => setForm({...form, client_id: e.target.value})} style={inputStyle}>
            <option value="">Select Client *</option>
            {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
          </select>
          <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
            <div style={{ flex: 1, minWidth: 140 }}>
              <label style={{ fontSize: 12, color: TEXT_MUTED, display: 'block', marginBottom: 4 }}>Report Date</label>
              <input type="date" value={form.report_date} onChange={e => setForm({...form, report_date: e.target.value})} style={inputStyle} />
            </div>
            <div style={{ flex: 1, minWidth: 140 }}>
              <label style={{ fontSize: 12, color: TEXT_MUTED, display: 'block', marginBottom: 4 }}>Violation Type</label>
              <select value={form.violation_type} onChange={e => setForm({...form, violation_type: e.target.value})} style={inputStyle}>
                <option value="">Select *</option>
                <option>Missed Check-Ins</option><option>Failed Drug Test</option><option>Missed PO Visit</option><option>Wrong Location</option><option>Missed Court Date</option><option>Multiple Violations</option>
              </select>
            </div>
          </div>
          <textarea placeholder="Describe the violation in detail *" value={form.description} onChange={e => setForm({...form, description: e.target.value})} style={{ ...inputStyle, minHeight: 100 }} />
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: 10, marginBottom: 12 }}>
            <div><label style={{ fontSize: 12, color: TEXT_MUTED, display: 'block', marginBottom: 4 }}>Missed Check-Ins</label><input type="number" min="0" value={form.missed_checkins} onChange={e => setForm({...form, missed_checkins: parseInt(e.target.value)})} style={{ ...inputStyle, padding: 10, marginBottom: 0 }} /></div>
            <div><label style={{ fontSize: 12, color: TEXT_MUTED, display: 'block', marginBottom: 4 }}>Last Check-In Date</label><input type="date" value={form.last_checkin} onChange={e => setForm({...form, last_checkin: e.target.value})} style={{ ...inputStyle, padding: 10, marginBottom: 0 }} /></div>
            <div><label style={{ fontSize: 12, color: TEXT_MUTED, display: 'block', marginBottom: 4 }}>Failed Drug Tests</label><input type="number" min="0" value={form.drug_test_failures} onChange={e => setForm({...form, drug_test_failures: parseInt(e.target.value)})} style={{ ...inputStyle, padding: 10, marginBottom: 0 }} /></div>
            <div><label style={{ fontSize: 12, color: TEXT_MUTED, display: 'block', marginBottom: 4 }}>Missed PO Visits</label><input type="number" min="0" value={form.missed_po_visits} onChange={e => setForm({...form, missed_po_visits: parseInt(e.target.value)})} style={{ ...inputStyle, padding: 10, marginBottom: 0 }} /></div>
          </div>
          <textarea placeholder="Recommended action (e.g. return to court, increase check-in frequency)" value={form.recommended_action} onChange={e => setForm({...form, recommended_action: e.target.value})} style={{ ...inputStyle, minHeight: 70 }} />
          <input placeholder="Submitted to (e.g. Officer Martinez, Sarasota County Court)" value={form.submitted_to} onChange={e => setForm({...form, submitted_to: e.target.value})} style={{ ...inputStyle, marginBottom: 16 }} />
          <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
            <button onClick={() => handleSave('draft')} disabled={saving} style={{ flex: 1, minWidth: 120, padding: 12, background: 'rgba(255,255,255,0.04)', color: TEXT, border: `0.5px solid ${BORDER}`, borderRadius: 8, fontSize: 14, cursor: 'pointer' }}>Save as Draft</button>
            <button onClick={() => handleSave('submitted')} disabled={saving || !form.client_id || !form.violation_type || !form.description} style={{ flex: 2, minWidth: 160, padding: 12, background: RED, color: 'white', border: 'none', borderRadius: 8, fontSize: 14, cursor: 'pointer', fontWeight: 'bold' }}>{saving ? 'Saving...' : '⚠️ Save & Mark Submitted'}</button>
          </div>
        </div>
      )}

      {reports.length === 0 ? (
        <div style={{ textAlign: 'center', padding: 40, color: TEXT_MUTED }}>
          <p style={{ fontSize: 40, marginBottom: 12 }}>✅</p>
          <p>No violation reports. All clients are in compliance.</p>
        </div>
      ) : reports.map(r => {
        const s = statusColors[r.status] || statusColors.draft;
        return (
          <div key={r.id} style={{ background: CARD_BG, border: `0.5px solid ${BORDER}`, borderRadius: 10, padding: 16, marginBottom: 10 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8, flexWrap: 'wrap', gap: 10 }}>
              <div>
                <p style={{ margin: 0, fontWeight: 'bold', color: TEXT }}>{r.clients?.name}</p>
                <p style={{ margin: '3px 0 0', fontSize: 13, color: RED, fontWeight: 'bold' }}>{r.violation_type}</p>
                <p style={{ margin: '3px 0 0', fontSize: 12, color: TEXT_DIM }}>{new Date(r.report_date).toLocaleDateString()}</p>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 8 }}>
                <span style={{ padding: '4px 12px', borderRadius: 20, fontSize: 12, fontWeight: 'bold', background: s.bg, color: s.color }}>{r.status.toUpperCase()}</span>
                <button onClick={() => printReport(r)} style={{ padding: '5px 12px', background: ACCENT, color: 'white', border: 'none', borderRadius: 6, fontSize: 12, cursor: 'pointer' }}>🖨️ Print</button>
              </div>
            </div>
            <p style={{ margin: 0, fontSize: 13, color: TEXT_MUTED }}>{r.description?.substring(0, 150)}{r.description?.length > 150 ? '...' : ''}</p>
          </div>
        );
      })}
    </div>
  );
}
