
CREATE TABLE public."Schedule" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  client_id bigint REFERENCES public."Clients"(id),
  provider_id bigint REFERENCES public."Providers"(id),
  appointment_date timestamp with time zone,
  appointment_description text,
  completed boolean default false
);

ALTER TABLE public."Schedule" ENABLE ROW LEVEL SECURITY;
