
CREATE TABLE public."Providers" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  provider_name text,
  contact_email text,
  phone text,
  county text,
  program_type text
);

ALTER TABLE public."Providers" ENABLE ROW LEVEL SECURITY;
