
CREATE TYPE alert_type_enum AS ENUM (
  'Missed Check-in',
  'Late',
  'Wrong Location'
);

CREATE TYPE alert_color_enum AS ENUM (
  'Red',
  'Yellow',
  'Orange'
);

CREATE TABLE public."Alerts" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  client_id bigint REFERENCES public."Clients"(id),
  provider_id bigint REFERENCES public."Providers"(id),
  alert_type alert_type_enum,
  alert_color alert_color_enum,
  alert_date timestamp with time zone default now(),
  resolved boolean default false,
  notes text
);

ALTER TABLE public."Alerts" ENABLE ROW LEVEL SECURITY;
